version: '3.8'

services:
  bd_balsamoa:
    image: postgres:15
    container_name: postgres_balsamoa
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: balsamoa_db
    ports:
      - "5432:5432"
    volumes:
      - balsamoa_data:/var/lib/postgresql/data

volumes:
  balsamoa_data: